"""Tasks.md generation.

Reads all tickets and Project.md, produces a dashboard. This file is
overwritten in full on every regeneration — never hand-edit it.
"""

from __future__ import annotations

from datetime import date, datetime
from pathlib import Path
from typing import Optional

import yaml

from .lint import get_blocked_tickets
from .paths import PROJECT_FILE, TASKS_FILE
from .ticket import FRONTMATTER_RE, Ticket, load_all_tickets

RECENT_DONE_LIMIT = 10


def _read_focus(root: Path) -> Optional[str]:
    """Pull the `focus` field from Project.md frontmatter, if present."""
    project_path = root / PROJECT_FILE
    if not project_path.exists():
        return None
    text = project_path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        return None
    try:
        fm = yaml.safe_load(match.group("frontmatter")) or {}
    except yaml.YAMLError:
        return None
    if isinstance(fm, dict):
        focus = fm.get("focus")
        return str(focus) if focus else None
    return None


def _format_progress(ticket: Ticket) -> str:
    """Format a ticket's subtask + checkbox progress for display."""
    parts = []
    sub_done, sub_total = ticket.subtask_progress()
    if sub_total:
        parts.append(f"subtasks: {sub_done}/{sub_total}")
    cb_done, cb_total = ticket.checkbox_progress()
    if cb_total:
        parts.append(f"checkboxes: {cb_done}/{cb_total}")
    return " · ".join(parts)


def _format_ticket_line(ticket: Ticket, *, include_notes: bool = False, include_progress: bool = False) -> str:
    """Render a single ticket entry as a Markdown bullet."""
    line = f"- **{ticket.id}** {ticket.title} [{ticket.priority}]"
    if include_notes and ticket.notes:
        line += f" — {ticket.notes}"
    if include_progress:
        progress = _format_progress(ticket)
        if progress:
            line += f"\n  - {progress}"
    return line


def generate_tasks_md(root: Path) -> str:
    """Render Tasks.md content as a string. Caller writes it to disk."""
    tickets_dir = root / "docs/ai/tickets"
    tickets = load_all_tickets(tickets_dir)
    focus = _read_focus(root)

    # Bucket tickets by status. We sort within each bucket so output is stable.
    by_status: dict[str, list[Ticket]] = {
        "in-progress": [],
        "blocked": [],
        "todo": [],
        "done": [],
    }
    for t in tickets:
        if t.status in by_status:
            by_status[t.status].append(t)

    # Priority sort key: high < medium < low (high first), then by id.
    priority_rank = {"high": 0, "medium": 1, "low": 2}

    def _sort_key(t: Ticket):
        return (priority_rank.get(t.priority, 3), t.id)

    for key in by_status:
        by_status[key].sort(key=_sort_key)

    # `done` is sorted by closed date descending instead, so "recent" works.
    by_status["done"].sort(key=lambda t: t.closed or date.min, reverse=True)

    blocked_map = get_blocked_tickets(tickets)

    # Stats
    total = len(tickets)
    type_counts: dict[str, int] = {}
    for t in tickets:
        type_counts[t.type] = type_counts.get(t.type, 0) + 1

    # ---- render ----

    out: list[str] = []
    out.append("# Tasks")
    out.append("")
    out.append(
        f"> Auto-generated by `bora status` on "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}. Do not hand-edit."
    )
    out.append("")

    if focus:
        out.append("## Current focus")
        out.append("")
        out.append(focus)
        out.append("")

    # In progress
    in_progress = by_status["in-progress"]
    out.append(f"## In progress ({len(in_progress)})")
    out.append("")
    if in_progress:
        for t in in_progress:
            out.append(_format_ticket_line(t, include_notes=True, include_progress=True))
    else:
        out.append("_No tickets in progress._")
    out.append("")

    # Blocked
    blocked = by_status["blocked"]
    # Also include tickets that are not status=blocked but have unfinished dependencies.
    # Only surface them once — prefer the explicit blocked status if both apply.
    explicit_blocked_ids = {t.id for t in blocked}
    implicit_blocked = [
        t for t in tickets
        if t.id in blocked_map
        and t.id not in explicit_blocked_ids
        and t.status != "done"
    ]
    out.append(f"## Blocked ({len(blocked) + len(implicit_blocked)})")
    out.append("")
    if blocked or implicit_blocked:
        for t in blocked:
            line = _format_ticket_line(t, include_notes=True)
            if t.id in blocked_map:
                line += f"\n  - depends on: {', '.join(blocked_map[t.id])}"
            out.append(line)
        for t in implicit_blocked:
            line = _format_ticket_line(t)
            line += f"\n  - depends on: {', '.join(blocked_map[t.id])} (not yet marked blocked)"
            out.append(line)
    else:
        out.append("_No blocked tickets._")
    out.append("")

    # Up next
    todo = by_status["todo"]
    # Filter out tickets that are blocked-by-deps from "Up next" since they're not
    # actually actionable yet. They appear in Blocked above.
    actionable_todo = [t for t in todo if t.id not in blocked_map]
    out.append(f"## Up next ({len(actionable_todo)})")
    out.append("")
    if actionable_todo:
        for t in actionable_todo:
            out.append(_format_ticket_line(t))
    else:
        out.append("_No actionable todo tickets._")
    out.append("")

    # Recently completed
    done = by_status["done"]
    recent_done = done[:RECENT_DONE_LIMIT]
    out.append(f"## Recently completed (last {len(recent_done)} of {len(done)})")
    out.append("")
    if recent_done:
        for t in recent_done:
            closed_str = t.closed.isoformat() if t.closed else "?"
            out.append(f"- **{t.id}** {t.title} (closed {closed_str})")
    else:
        out.append("_No completed tickets yet._")
    out.append("")

    # Stats
    out.append("## Stats")
    out.append("")
    status_summary = " · ".join(
        f"{len(by_status[s])} {s}" for s in ("done", "todo", "in-progress", "blocked")
    )
    out.append(f"- Total: {total} tickets · {status_summary}")
    if type_counts:
        type_summary = " · ".join(
            f"{count} {t}" for t, count in sorted(type_counts.items(), key=lambda kv: -kv[1])
        )
        out.append(f"- By type: {type_summary}")
    out.append("")

    return "\n".join(out)


def write_tasks_md(root: Path) -> Path:
    """Generate and write Tasks.md. Returns the path written."""
    content = generate_tasks_md(root)
    path = root / TASKS_FILE
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path
